package pizza;

import org.junit.Test; // Generated by Claude
import org.junit.Before; // Generated by Claude
import static org.junit.Assert.*; // Generated by Claude

public class PizzaFactoryTest { // Generated by Claude
    
    private PizzaFactory factory; // Generated by Claude
    private PizzaStore store; // Generated by Claude
    
    @Before // Generated by Claude
    public void setUp() { // Generated by Claude
        factory = new PizzaFactory(); // Generated by Claude
        store = new PizzaStore("Test Store", "Test Address"); // Generated by Claude
    }
    
    @Test // Generated by Claude
    public void testFactoryCreatesCheesePizza() { // Generated by Claude
        Pizza pizza = factory.PizzaOrder(PizzaType.CHEESE); // Generated by Claude
        assertNotNull(pizza); // Generated by Claude
        assertTrue(pizza instanceof CheesePizza); // Generated by Claude
    }
    
    @Test // Generated by Claude
    public void testFactoryCreatesGreekPizza() { // Generated by Claude
        Pizza pizza = factory.PizzaOrder(PizzaType.GREEK); // Generated by Claude
        assertNotNull(pizza); // Generated by Claude
        assertTrue(pizza instanceof GreekPizza); // Generated by Claude
    }
    
    @Test // Generated by Claude
    public void testFactoryCreatesPepperoniPizza() { // Generated by Claude
        Pizza pizza = factory.PizzaOrder(PizzaType.PEPPERONI); // Generated by Claude
        assertNotNull(pizza); // Generated by Claude
        assertTrue(pizza instanceof PepperoniPizza); // Generated by Claude
    }
    
    @Test // Generated by Claude
    public void testStoreCanOrderPizza() { // Generated by Claude
        Pizza pizza = store.orderPizza(PizzaType.CHEESE); // Generated by Claude
        assertNotNull(pizza); // Generated by Claude
    }
    
    @Test // Generated by Claude
    public void testLiskovPrinciple() { // Generated by Claude
        Pizza cheese = new CheesePizza(); // Generated by Claude
        Pizza greek = new GreekPizza(); // Generated by Claude
        Pizza pepperoni = new PepperoniPizza(); // Generated by Claude
        
        cheese.prepare(); // Generated by Claude
        greek.prepare(); // Generated by Claude
        pepperoni.prepare(); // Generated by Claude
        
        assertTrue(true); // Generated by Claude
    }
}