package pizza;

public class PizzaStore {
    private String name;
    private String address;
    private PizzaFactory pizzaFactory; // Generated by Claude

    public PizzaStore(String name, String address) {
        this.name = name;
        this.address = address;
        this.pizzaFactory = new PizzaFactory(); // Generated by Claude
    }

    public Pizza orderPizza(PizzaType type) { // Generated by Claude
        // Generated by Claude
        Pizza pizza = pizzaFactory.PizzaOrder(type); // Generated by Claude
        
        if (pizza != null) { // Generated by Claude
            pizza.prepare(); // Generated by Claude
            pizza.bake(); // Generated by Claude
            pizza.cut(); // Generated by Claude
            pizza.box(); // Generated by Claude
        }
        
        return pizza; // Generated by Claude
    }

    public void demonstrateLiskov() { // Generated by Claude
        System.out.println("=== Liskov Substitution Principle Demo ==="); // Generated by Claude
        
        // Generated by Claude
        Pizza[] pizzas = { // Generated by Claude
            new CheesePizza(), // Generated by Claude
            new GreekPizza(), // Generated by Claude
            new PepperoniPizza() // Generated by Claude
        }; // Generated by Claude
        
        for (Pizza pizza : pizzas) { // Generated by Claude
            pizza.prepare(); // Generated by Claude
        } // Generated by Claude
    }

    public static void main(String[] args) {
        PizzaStore store = new PizzaStore("CT Pizza", "New Haven"); // Generated by Claude
        
        System.out.println("Welcome to " + store.name); // Generated by Claude
        
        // Generated by Claude
        System.out.println("\nOrdering Cheese Pizza:"); // Generated by Claude
        store.orderPizza(PizzaType.CHEESE); // Generated by Claude
        
        System.out.println("\nOrdering Greek Pizza:"); // Generated by Claude
        store.orderPizza(PizzaType.GREEK); // Generated by Claude
        
        // Generated by Claude
        store.demonstrateLiskov(); // Generated by Claude
    }

    public String getName() {
        return name;
    }

    public String getAddress() {
        return address;
    }
}